service: my-cbd-store

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-2

  environment:
    tableName: CBD-Store
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: CBD-Store
          method: post
          authorizer: aws_iam

  get:
    handler: get.main
    events:
      - http:
          path: CBD-Store/{id}
          method: get
          authorizer: aws_iam

  list:
    handler: list.main
    events:
      - http:
          path: CBD-Store
          method: get
          authorizer: aws_iam

  update:
    handler: update.main
    events:
      - http:
          path: CBD-Store/{id}
          method: put
          authorizer: aws_iam

  delete:
    handler: delete.main
    events:
      - http:
          path: CBD-Store/{id}
          method: delete
          authorizer: aws_iam

  billing:
    handler: billing.main
    events:
      - http:
          path: billing
          method: post
          authorizer: aws_iam
